@startuml
left to right direction
skinparam actorStyle hollow
/'Guest'/

Guest --> (view products)
Guest --> (register)
Guest --> (login)

/'User - authenticated'/
User --> (view products)
User --> (add products to cart)
User --> (create order)
User --> (manage account data)
User --> (view past orders)
User --> (leave feedback about product - optional)
User --> (cancel order)
User --> (refund products)
User --> (logout)

/'Admin - shop executive'/

Admin --> (manage users and their accounts)
Admin --> (manage orders)
Admin --> (view orders)
Admin --> (manage account data)
Admin --> (manage products)
Admin --> (logout)



@enduml