@startuml
left to right direction
state PrzetwarzanieSugestii {
  state Tworzenie{
    state Przygotowywana
    [*] --> Przygotowywana
    Przygotowywana --> [*]
  }
  [*] --> Tworzenie
  Tworzenie --> Zgłoszona
  state Edytowana{
  state "Wprowadzanie zmian" as zmiany
  [H] --> zmiany
  zmiany --> [*]
}
  Edytowana --> Zgłoszona
  Zgłoszona --> Edytowana
  Zgłoszona --> Odrzucona
  Zgłoszona --> Zaakceptowana
  Odrzucona --> [*]
  Zaakceptowana --> [*]
}
@enduml