@startuml
left to right direction

actor :Użytkownik zalogowany:

(Użytkownik zalogowany) --> (otwarcie formularza tworzenia sugestii)
(otwarcie formularza tworzenia sugestii) .> (wprowadzenie sugerowanych zmian w formularzu) : <<Extends>>
(wprowadzenie sugerowanych zmian w formularzu) .>  (zgłoszenie sugestii) : <<Extends>>

(Użytkownik zalogowany) --> (przeglądanie własnych sutgestii)
@enduml
