server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  level:
    root: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
        - AuthenticationFilter
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/product/**
        filters:
        - RewritePath=/product/(?<path>.*), /$\{path}
        - AuthenticationFilter
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
        - AuthenticationFilter
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      - id: authorization-service
        uri: lb://AUTHORIZATION-SERVICE
        predicates:
          - Path=/auth/**
        filters:
          - AuthenticationFilter

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: product
        url: /v3/api-docs/product
      - name: order
        url: /v3/api-docs/order


management:
  tracing:
    sampling:
      probability: 1.0