server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

springdoc:
  packagesToScan: com.tks.microservices.userservice

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0
